import 'package:example/assets.dart';
import 'package:flutter/material.dart';
import 'package:deposits_ui_kit_v2/deposits_ui_kit_v2.dart';

class ComponentsDocPage extends StatefulWidget {
  const ComponentsDocPage({super.key});

  @override
  State<ComponentsDocPage> createState() => _ComponentsDocPageState();
}

class _ComponentsDocPageState extends State<ComponentsDocPage> {
  String? selectedValue;
  final TextEditingController textEditingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
      color: AppColors.whiteColor,
      child: Column(
        children: [
          const DepositsH4Text(text: "Content Cards"),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const VSpacerWidget(size: 10.0),
              DepositsContentCardOne(
                title: "Title here",
                subtitle: "Add a short description here",
                image: addIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentCardOne(
                title: "Linked Banks & Cards",
                subtitle: "View your linked banks & cards",
                image: cardIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentCardOne(
                title: "Set up Direct Deposit ",
                subtitle: "Get your paycheck 2 days earlier",
                image: receiveSquareIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentCardOne(
                title: "Top up your account",
                subtitle: "Add funds to your wallet",
                image: addIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentCardOne(
                title: "Identity Verification",
                subtitle: "Let’s get you verified",
                image: verifyIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              const VSpacerWidget(size: 10.0),
              DepositsContentCardTwo(
                  title: "Title",
                  subtitle:
                      "Short description that doesn’t exceeds two lines for horizontal list or 3 for vertical list items",
                  badgeTitle: "Neutral",
                  badgeBgColor: AppColors.neutral500Color,
                  imageColor: AppColors.neutral500Color,
                  image: routingIcon,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentCardTwo(
                  title: "Title",
                  subtitle:
                      "Short description that doesn’t exceeds two lines for horizontal list or 3 for vertical list items",
                  badgeTitle: "Neutral",
                  badgeBgColor: AppColors.blue500Color,
                  imageColor: AppColors.blue500Color,
                  arrowColor: AppColors.blue500Color,
                  image: routingIcon,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentCardTwo(
                  title: "Promo / Perks",
                  subtitle:
                      "Get the latest promotion code here, You can save money every time for any kind of shopping!",
                  badgeTitle: "new",
                  badgeBgColor: AppColors.neutral500Color,
                  imageColor: AppColors.green600Color,
                  image: starIcon,
                  arrowColor: AppColors.transparentColor,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentCardTwo(
                  title: "Find an ATM ",
                  subtitle:
                      "Search and discover the closest ATM near you anywhere, anytime.",
                  badgeTitle: "new",
                  badgeBgColor: AppColors.neutral500Color,
                  imageColor: AppColors.green600Color,
                  image: routingIcon,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              const VSpacerWidget(size: 5.0),
              DepositsContentLabelOne(
                  title: "This is a header / Title",
                  subtitle:
                      "This is a subheader that further gives context to the header",
                  arrowColor: AppColors.transparentColor,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentLabelOne(
                  title: "This is a header / Title",
                  subtitle:
                      "This is a subheader that further gives context to the header",
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentLabelTwo(
                  title: "Suitable for you",
                  subtitle: "New features, explore now.",
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentLabelThree(
                  title: "See all transactions", onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentLabelOne(
                  title: "About this promo",
                  subtitle:
                      "Recognized as a global leader in interactive and digital entertainment, Sony Interactive Entertainment (SIE) is responsible for the PlayStation® brand and family of products and services. PlayStation has delivered innovation to the market since the launch of the original PlayStation in Japan in 1994.",
                  arrowColor: AppColors.transparentColor,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentLabelFour(
                  title: "Verify your phone number",
                  subtitleOne:
                      "Please enter the verification code sent to XXX 834, ",
                  subtitleTwo: "Wrong Number? Change Number.",
                  arrowColor: AppColors.transparentColor,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentListOne(
                title: "Request",
                subtitle:
                    "Request to get paid, send an invoice or ask your payer to scan a QR",
                image: arrowUpIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListTwo(
                title: "Label",
                subtitle: "Short description",
                image: arrowUpIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListThree(
                title: "Payment types",
                subtitle: "Enable 2FA authentication",
                image: walletAddIcon,
                arrowText: "Apple Pay",
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListFour(
                title: "Unfreeze card",
                image: sunIcon,
                badgeText: "Card frozen",
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListFive(
                title: "2FA Authentication",
                subtitle: "Enable 2FA authentication",
                onTapped: (a) {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListSix(
                  title: "2FA Authentication",
                  subtitle: "Enable 2FA authentication",
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentListSeven(
                  title: "2FA Authentication",
                  subtitle: "Enable 2FA authentication",
                  badgeText: "Green",
                  badgeBgColor: AppColors.green600Color,
                  badgeTextColor: AppColors.whiteColor,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentListEight(
                title: "Sophia Alexander",
                subtitle: "sophiaalexander@gmail.com",
                image: profileCircleIcon,
                imageBgColor: AppColors.brand100Color,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListEight(
                title: "Grocery receipt   ",
                subtitle: "9:40pm",
                image: receiptTextIcon,
                imageBgColor: AppColors.brand100Color,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListNine(
                  title: "Check 001",
                  subtitle: "Feb 02, 9:40pm",
                  amount: "\$1,090.15",
                  image: checkIcon,
                  imageBgColor: AppColors.brand100Color,
                  badgeText: "Processing",
                  badgeBgColor: AppColors.blue200Color,
                  badgeTextColor: AppColors.blue600Color,
                  onTapped: () {}),
              const VSpacerWidget(size: 5.0),
              DepositsContentListTen(
                title: "\$536.80",
                subtitleOne: "Due in ",
                subtitleOneColor: AppColors.textPrimaryColor,
                subtitleTwo: " 3 days",
                subtitleTwoColor: AppColors.textSecondaryColor,
                bottomTitleOne: "Auto pay",
                bottomTitleOneColor: AppColors.textPrimaryColor,
                bottomTitleTwo: "(Disabled)",
                bottomTitleTwoColor: AppColors.textSecondaryColor,
                arrowText: "Make payment",
                formState: DepositsSwitchFormState.on,
                onTapped: () {},
                onChanged: (a) {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentListEleven(
                title: "Netflix",
                image: netflixIcon,
                bottomTitleOne: "****1234, +3 more",
                bottomTitleTwo: "Enabled on Apr 17, 2024, 3:59AM",
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentStarterOne(
                title: "Budget tracker",
                subtitle: "Take control of your spending",
                image: activityIcon,
                imageBgColor: AppColors.brand100Color,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentStarterOne(
                title: " Biometric Authentication",
                subtitle:
                    "Enabling this option will allow you to use your fingerprint or face to login if your device supports it",
                image: biometricIcon,
                imageBgColor: AppColors.transparentColor,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentStarterOne(
                title: "No transactions yet",
                subtitle: "Fund your wallet to send money and more",
                image: boxIcon,
                imageBgColor: AppColors.neutral100Color,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentStarterOne(
                title: "Verify your account",
                subtitle:
                    "This app will have access to the information below to help verify your account.",
                image: verifyAccountIcon,
                imageBgColor: AppColors.transparentColor,
                imageHeight: 80.0,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentStarterTwo(
                title: "Add receipt",
                subtitle:
                    "Save your receipts so they’re easy to find when you need them.",
                buttonOneText: "Take a picture",
                buttonOneIcon: Icons.camera_alt_outlined,
                buttonTwoText: "Upload instead",
                image: receiptTextGreyIcon,
                imageBgColor: AppColors.neutral100Color,
                onTapped: () {},
                onButtonOneTapped: () {},
                onButtonTwoTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentFeedbackOne(
                title: "Payment pending",
                subtitle:
                    "You have enabled automatic savings on spend, your spare change will be kept when you spend.",
                image: warningIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentFeedbackOne(
                title: "Payment successful",
                subtitle:
                    "You have enabled automatic savings on spend, your spare change will be kept when you spend.",
                image: successIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
              DepositsContentFeedbackOne(
                title: "Payment failed",
                subtitle:
                    "You have enabled automatic savings on spend, your spare change will be kept when you spend.",
                image: errorIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 5.0),
            ],
          ),
          const VSpacerWidget(size: 10.0),
          const DepositsH4Text(text: "Lists"),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const VSpacerWidget(size: 10.0),
              DepositsListTransaction(
                image: depositIcon,
                title: "From John Alves",
                subtitle: "Feb 02, 9:40pm",
                amount: "\$1,090.15",
                showBorderBottom: true,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListTransaction(
                image: withdrawIcon,
                title: "From John Alves",
                subtitle: "Feb 02, 9:40pm",
                amount: "-\$1,090.15",
                showBorderBottom: true,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListTransaction(
                image: addFundIcon,
                title: "Account funding",
                subtitle: "Feb 02, 9:40pm",
                amount: "\$1,090.15",
                showBorderBottom: true,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListTransactionItem(
                amount: "\$127.34",
                accountName: "Brooke Kennedy",
                bankName: "Bank of America",
                accountNumber: "****5679",
                recipientName: "Owen Brandon",
                recipientEmail: "(owenbrandy@email.com)",
                recipientAccountNumber: "****5679",
                routingNumber: "9324237540",
                phoneNumber: "(917) 744-9158",
                note: "Uber fee",
                fee: "\$1.3",
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListTransactionItem(
                amount: "\$127.34",
                recipientName: "Owen Brandon",
                recipientEmail: "(owenbrandy@email.com)",
                note: "Uber fee",
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCardAccountOne(
                title: "Wells Fargo",
                subtitle: "Ending ****8350",
                image: AppBankIcons.bankWellsFargo,
                badgeText: "verified",
                badgeBgColor: AppColors.green200Color,
                badgeTextColor: AppColors.green700Color,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCardAccountTwo(
                title: "Visa",
                subtitle: "Ending ****8350",
                image: AppCardIcons.cardVisa,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCardAccountThree(
                title: "Visa",
                subtitle: "Ending ****8350",
                image: AppCardIcons.cardVisa,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCardAccountFour(
                title: "Wells Fargo",
                subtitle: "Ending ****8350",
                image: AppBankIcons.bankWellsFargo,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCardAccountFive(
                title: "Wells Fargo",
                subtitle: "Ending ****8350",
                image: AppBankIcons.bankWellsFargo,
                items: [
                  DepositsBankAccountListModel(
                    name: "Bank of America",
                    bankLogo: DepositsBankLogos.bankBankOfAmerica.toString(),
                    description: "Ending ****8350",
                  ),
                  DepositsBankAccountListModel(
                    name: "Bank of America",
                    bankLogo: DepositsBankLogos.bankBankOfAmerica.toString(),
                    description: "Ending ****9050",
                  ),
                  DepositsBankAccountListModel(
                    name: "Bank of America",
                    bankLogo: DepositsBankLogos.bankBankOfAmerica.toString(),
                    description: "Ending ****8190",
                  ),
                ],
                onTapped: (a) {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCardAccountSix(
                title: "Discover",
                subtitle: "Ending ****8350",
                image: AppCardIcons.cardDiscover,
                badgeText: "",
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "First Name",
                subtitle: "Francis",
                showVisibleIcon: false,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Last Name",
                subtitle: "Knight",
                showVisibleIcon: false,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Card PAN",
                subtitle: "5399 0123 4567 8901",
                showVisibleIcon: true,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Address",
                subtitle: "Suite 102 Gary Levin Avenue, Bay Area, CA",
                showVisibleIcon: true,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Billing Address",
                subtitle: "Suite 102 Gary Levin Avenue, Bay Area, CA",
                showVisibleIcon: false,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Routing Number",
                subtitle: "041 215 663",
                showVisibleIcon: true,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Account Number",
                subtitle: "88 8369 3592",
                showVisibleIcon: true,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Card Expiry",
                subtitle: "09/26",
                showVisibleIcon: true,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "CVV",
                subtitle: "123",
                showVisibleIcon: true,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListCopyField(
                title: "Card PIN",
                subtitle: "0000",
                showVisibleIcon: true,
                isVisible: false,
                onCopyIconTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListChecklistOne(
                title:
                    "We’ll require the following KYC information to issue you a new debit card:",
                titleColor: AppColors.textSecondaryColor,
                items: [
                  DepositsChecklistModel(
                    title: "Valid email address",
                    titleColor: AppColors.textSecondaryColor,
                    icon: Icons.check_rounded,
                    iconColor: AppColors.green600Color,
                    iconBgColor: AppColors.success100Color,
                  ),
                  DepositsChecklistModel(
                    title: "Valid phone number ",
                    titleColor: AppColors.textSecondaryColor,
                    icon: Icons.check_rounded,
                    iconColor: AppColors.green600Color,
                    iconBgColor: AppColors.success100Color,
                  ),
                  DepositsChecklistModel(
                    title: "Personal details(SSN, Date of birth and more)",
                    titleColor: AppColors.textSecondaryColor,
                    icon: Icons.check_rounded,
                    iconColor: AppColors.green600Color,
                    iconBgColor: AppColors.success100Color,
                  ),
                ],
              ),
              const VSpacerWidget(size: 10.0),
              DepositsListChecklistTwo(
                title:
                    "We’ll require the following KYC information to issue you a new debit card:",
                titleColor: AppColors.textPrimaryColor,
                items: [
                  DepositsChecklistModel(
                    title: "Valid email address",
                    titleColor: AppColors.textPrimaryColor,
                    icon: Icons.check_rounded,
                    iconColor: AppColors.whiteColor,
                    iconBgColor: AppColors.green600Color,
                  ),
                  DepositsChecklistModel(
                    title: "Valid phone number ",
                    titleColor: AppColors.textPrimaryColor,
                    icon: Icons.check_rounded,
                    iconColor: AppColors.whiteColor,
                    iconBgColor: AppColors.green600Color,
                  ),
                  DepositsChecklistModel(
                    title: "Personal details(SSN, Date of birth and more)",
                    titleColor: AppColors.textPrimaryColor,
                    icon: Icons.check_rounded,
                    iconColor: AppColors.whiteColor,
                    iconBgColor: AppColors.green600Color,
                  ),
                ],
                buttonText: "Request Debit Card",
                buttonBgColor: AppColors.gwGreen100Color,
                buttonTextColor: AppColors.gwTextColor,
                onButtonClicked: () {},
                footnoteText:
                    "Typically takes about 3-5 minutes to complete the entire process.",
                footnoteColor: AppColors.neutral500Color,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "Perks card"),
              const VSpacerWidget(size: 10.0),
              Row(
                children: [
                  DepositsCardPerk(
                    image: psIcon,
                    title: "PlayStation",
                    subtitle: "Up to 90% off ",
                    bottomTitle: "Expires in 3 days",
                    subtitleColor: AppColors.primaryColor,
                  ),
                ],
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "Summary card"),
              const VSpacerWidget(size: 10.0),
              Container(
                color: AppColors.docBgColor,
                padding: const EdgeInsets.all(5.0),
                child: Column(
                  children: [
                    const DepositsCardSummary(
                      heading: "Outgoing payouts",
                      title: "On the way to your bank account",
                      subtitleOne:
                          "These funds should arrive in your bank account soon. Payouts are scheduled to ",
                      subtitleTwo: "automatically send daily",
                      bottomTitle: "Total",
                      bottomSubtitle: "\$33,054.00",
                    ),
                    const VSpacerWidget(size: 10.0),
                    DepositsCardSummaryFull(
                      title: "Payouts",
                      subtitle:
                          "Detailed breakdown of the total payouts line from the above Balance Summary report. Includes changes to your Modo balance, from payouts to your bank, as well as itemised downloads.",
                      bottomTitle: "Charges",
                      bottomCardOneTitle: "By Stripe",
                      bottomCardOneTitleColor: const Color(0xff6259FA),
                      bottomCardOneBgColor: const Color(0xffF0F0F9),
                      bottomCardOneItems: [
                        DepositsCardSummaryFullModel(
                          title: "Count",
                          titleColor: AppColors.neutral700Color,
                          subtitle: "5",
                          subtitleColor: AppColors.neutral700Color,
                        ),
                        DepositsCardSummaryFullModel(
                          title: "Gross Amount",
                          titleColor: AppColors.neutral700Color,
                          subtitle: "\$2,654.00",
                          subtitleColor: AppColors.neutral700Color,
                        ),
                      ],
                      bottomCardTwoTitle: "Moov",
                      bottomCardTwoTitleColor: const Color(0xffD62F4B),
                      bottomCardTwoBgColor: const Color(0xffFEDADF),
                      bottomCardTwoItems: [
                        DepositsCardSummaryFullModel(
                          title: "Count",
                          titleColor: AppColors.neutral700Color,
                          subtitle: "5",
                          subtitleColor: AppColors.neutral700Color,
                        ),
                        DepositsCardSummaryFullModel(
                          title: "Gross Amount",
                          titleColor: AppColors.neutral700Color,
                          subtitle: "\$2,654.00",
                          subtitleColor: AppColors.neutral700Color,
                        ),
                      ],
                    ),
                    const VSpacerWidget(size: 10.0),
                  ],
                ),
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "Target progress card"),
              const VSpacerWidget(size: 10.0),
              const DepositsCardTargetProgressCard(
                title: "Wedding",
                subtitle: "Recurring",
                percent: 20,
                amountOne: "\$1,077.00",
                amountTwo: "\$5,000.00",
                progressColor: AppColors.blue200Color,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsProgressbar(
                percent: 10,
                color: AppColors.blue200Color,
              ),
              const VSpacerWidget(size: 4.0),
              const DepositsProgressbar(
                percent: 30,
                color: AppColors.blue200Color,
              ),
              const VSpacerWidget(size: 4.0),
              const DepositsProgressbar(
                percent: 60,
                color: AppColors.blue200Color,
              ),
              const VSpacerWidget(size: 4.0),
              const DepositsProgressbar(
                percent: 80,
                color: AppColors.blue200Color,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "Card"),
              const VSpacerWidget(size: 10.0),
              DepositsCardBorderedOne(
                title: "Round up to the nearest dollar",
                subtitle:
                    "If you spend \$36.29, \$37 is deducted and \$0.71 is saved. ",
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsCardBorderedTwo(
                title: "Round up to the nearest dollar",
                subtitle:
                    "If you spend \$36.29, \$37 is deducted and \$0.71 is saved. ",
                image: lockIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsCardBorderedThree(
                  title: "Round up to the nearest dollar",
                  subtitle:
                      "If you spend \$36.29, \$37 is deducted and \$0.71 is saved.",
                  image: flashIcon,
                  activeBankTitle: "Wells Fargo",
                  activeBankSubtitle: "Ending ****8350",
                  activeBankImage: AppBankIcons.bankWellsFargo.toString(),
                  bankList: [
                    DepositsBankAccountListModel(
                      name: "Citi bank",
                      bankLogo: AppBankIcons.bankCiti.toString(),
                      description: "Ending ****8350",
                    ),
                    DepositsBankAccountListModel(
                      name: "US bank",
                      bankLogo: AppBankIcons.bankTemplateThree.toString(),
                      description: "Ending ****9050",
                    ),
                    DepositsBankAccountListModel(
                      name: "Bank of America",
                      bankLogo: AppBankIcons.bankBankOfAmerica.toString(),
                      description: "Ending ****8190",
                    ),
                  ],
                  processingFeeIcon: Icons.info,
                  processingFeeText:
                      "You will be charged \$7.20 processing fee.",
                  buttonText: "Add a new card",
                  buttonIconWidget: Container(
                    padding: const EdgeInsets.all(2),
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(30.0),
                      color: const Color(0xff53E1C2),
                    ),
                    child: const Icon(
                      Icons.add,
                      size: 13.0,
                      color: AppColors.whiteColor,
                    ),
                  ),
                  onPressed: () {},
                  onAccountChanged: (a) {}),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "Invoice widget"),
              const VSpacerWidget(size: 10.0),
              DepositsCardInvoice(
                title: "Invoice",
                addText: "Add an item",
                totalText: "Total cost",
                items: const [],
                onAddItemClicked: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsCardInvoice(
                title: "Invoice",
                addText: "Add an item",
                totalText: "Total cost",
                items: [
                  DepositsInvoiceItemModel(
                    title: "Travel bag",
                    amount: 90.0,
                    currency: "\$",
                  ),
                  DepositsInvoiceItemModel(
                    title: "Delivery",
                    amount: 55.0,
                    currency: "\$",
                  ),
                  DepositsInvoiceItemModel(
                    title: "Catering",
                    amount: 23.0,
                    currency: "\$",
                  ),
                  DepositsInvoiceItemModel(
                    title: "Transportation",
                    amount: 213.0,
                    currency: "\$",
                  ),
                ],
                onAddItemClicked: () {},
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "SCAN WIDGET"),
              const VSpacerWidget(size: 10.0),
              DepositsCardScanOne(
                centerWidget: Container(),
                buttonText: "Continue",
                onButtonPressed: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsCardScanTwo(
                centerWidget: Container(),
                buttonText: "Continue",
                onButtonPressed: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsCardScanThree(
                centerWidget: Container(),
                title:
                    "Move your debit/credit card into this area, make sure this is readable.",
                titleColor: AppColors.whiteColor,
                buttonText: "Continue",
                onButtonPressed: () {},
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "CARD DETAILS"),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsCardOne(
                items: [
                  DepositsCardDetailModel(
                    title: "Card PAN",
                    subtitle: "5399 0123 4567 8901",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "Card Expiry",
                    subtitle: "09 / **",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "CVV",
                    subtitle: "539",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "Card PIN",
                    subtitle: "5399",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: true,
                    centerWidget: Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 5.0,
                        vertical: 2.0,
                      ),
                      decoration: BoxDecoration(
                        color: AppColors.neutral100Color,
                        border: Border.all(
                          width: 1.0,
                          color: AppColors.neutral200Color,
                        ),
                        borderRadius: BorderRadius.circular(6.0),
                      ),
                      child: const DepositsFootnoteText(
                        text: "Change PIN",
                        color: AppColors.textPrimaryColor,
                      ),
                    ),
                  ),
                  DepositsCardDetailModel(
                    title: "Billing address",
                    subtitle: "Suite 102 Gary Levin Avenue, Bay Area, CA",
                    showVisibleIcon: false,
                    isVisible: true,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  )
                ],
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsCardTwo(
                title: "Your card details",
                titleColor: AppColors.textPrimaryColor,
                items: [
                  DepositsCardDetailModel(
                    title: "First Name",
                    subtitle: "Francis",
                    showVisibleIcon: false,
                    isVisible: true,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "Last Name",
                    subtitle: "Knight",
                    showVisibleIcon: false,
                    isVisible: true,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "Card PAN",
                    subtitle: "5399 0123 4567 8901",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "Card Expiry",
                    subtitle: "09 / **",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "CVV",
                    subtitle: "539",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "Card PIN",
                    subtitle: "5399",
                    showVisibleIcon: true,
                    isVisible: false,
                    showCopyIcon: true,
                    showCenterWidget: true,
                    centerWidget: Container(),
                  ),
                  DepositsCardDetailModel(
                    title: "Billing address",
                    subtitle: "Suite 102 Gary Levin Avenue, Bay Area, CA",
                    showVisibleIcon: false,
                    isVisible: true,
                    showCopyIcon: true,
                    showCenterWidget: false,
                    centerWidget: Container(),
                  )
                ],
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsMobileTable(
                title: "My Cards",
                onCardTapped: () {},
                items: [
                  DepositsCardMobileTableModel(
                    card: "****4589",
                    type: "Virtual",
                    balance: "\$208.50",
                  ),
                  DepositsCardMobileTableModel(
                    card: "****9086",
                    type: "Virtual",
                    balance: "\$75.00",
                  ),
                  DepositsCardMobileTableModel(
                    card: "****5403",
                    type: "Physical",
                    balance: "\$1208.50",
                  ),
                ],
                heading: const [
                  "Card",
                  "Type",
                  "Balance",
                ],
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsMobileTable(
                title: "My Accounts",
                icon: Icons.account_balance,
                onCardTapped: () {},
                items: [
                  DepositsCardMobileTableModel(
                    card: "****4589",
                    type: "Checking",
                    balance: "\$208.50",
                  ),
                  DepositsCardMobileTableModel(
                    card: "****9086",
                    type: "Savings",
                    balance: "\$75.00",
                  ),
                  DepositsCardMobileTableModel(
                    card: "****5403",
                    type: "Checking",
                    balance: "\$1208.50",
                  ),
                ],
                heading: const [
                  "Account",
                  "Type",
                  "Balance",
                ],
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(
                  text: "Multiple Card, card stack, MULTIPLE ACCOUNT card"),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsStackOne(
                title: "For Amazon ",
                titleColor: AppColors.neutral700Color,
                subtitleOne: "****4589",
                subtitleTwo: "Virtual",
                image: cardIcon,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsStackTwo(
                title: "Secondary account",
                titleColor: AppColors.neutral700Color,
                subtitle: "Ending ****5608",
                image: AppBankIcons.bankTemplateOne,
                onTapped: () {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsStackFormOne(
                title: "All accounts overview",
                image: AppBankIcons.bankTemplateTwo,
                onTapped: (a) {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsStackFormTwo(
                title: "All accounts (4)",
                titleColor: AppColors.whiteColor,
                image: AppBankIcons.bankTemplateThree,
                iconColor: AppColors.whiteColor,
                bgColor: AppColors.cyan600Color,
                borderColor: AppColors.cyan500Color,
                onTapped: (a) {},
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "MULTI CARD INDICATOR"),
              const VSpacerWidget(size: 10.0),
              Column(
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      DepositsDetailsCardIndicator(
                        totalIndex: 2,
                        activeIndex: 0,
                        onChanged: (a) {},
                      )
                    ],
                  ),
                  const VSpacerWidget(size: 10.0),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      DepositsDetailsCardIndicator(
                        totalIndex: 3,
                        activeIndex: 1,
                        onChanged: (a) {},
                      )
                    ],
                  ),
                  const VSpacerWidget(size: 10.0),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      DepositsDetailsCardIndicator(
                        totalIndex: 4,
                        activeIndex: 2,
                        onChanged: (a) {},
                      )
                    ],
                  ),
                  const VSpacerWidget(size: 10.0),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      DepositsDetailsCardIndicator(
                        totalIndex: 5,
                        activeIndex: 3,
                        onChanged: (a) {},
                      )
                    ],
                  ),
                  const VSpacerWidget(size: 10.0),
                ],
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsBalanceCardOne(
                title: "Balance",
                amount: "\$4,160.54",
                subtitle: "ID: example@gmail.com",
                subtitleBgColor: AppColors.neutral100Color,
                bgColor: AppColors.blue400Color,
                borderColor: AppColors.neutral200Color,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsBalanceCardOne(
                title: "Balance",
                titleColor: AppColors.neutral100Color,
                amount: "\$4,160.54",
                amountColor: AppColors.whiteColor,
                subtitle: "ID: example@gmail.com",
                subtitleColor: AppColors.whiteColor,
                subtitleBgColor: Color.fromRGBO(255, 255, 255, 0.15),
                bgColor: AppColors.blue400Color,
                borderColor: AppColors.neutral200Color,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsBalanceCardTwo(
                title: "\$4,160.54",
                titleColor: AppColors.textPrimaryColor,
                subtitle: "Available balance",
                subtitleColor: AppColors.textPrimaryColor,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsBalanceCardTwo(
                title: "\$4,160.54",
                titleColor: AppColors.textPrimaryColor,
                subtitle: "Available balance",
                subtitleColor: AppColors.textPrimaryColor,
                isVisible: false,
              ),
              const VSpacerWidget(size: 10.0),
              Container(
                color: AppColors.blue400Color,
                padding: const EdgeInsets.all(10.0),
                child: const Column(
                  children: [
                    VSpacerWidget(size: 10.0),
                    DepositsDetailsBalanceCardTwo(
                      title: "\$4,160.54",
                      titleColor: AppColors.whiteColor,
                      subtitle: "Available balance",
                      subtitleColor: AppColors.neutral100Color,
                    ),
                    VSpacerWidget(size: 10.0),
                    DepositsDetailsBalanceCardTwo(
                      title: "\$4,160.54",
                      titleColor: AppColors.whiteColor,
                      subtitle: "Available balance",
                      subtitleColor: AppColors.neutral100Color,
                      isVisible: false,
                    ),
                    VSpacerWidget(size: 10.0),
                  ],
                ),
              ),
              const VSpacerWidget(size: 10.0),
              Container(
                color: AppColors.blue400Color,
                padding: const EdgeInsets.all(10.0),
                child: Column(
                  children: [
                    const VSpacerWidget(size: 10.0),
                    DepositsDetailsBalanceCardThree(
                      title: "Credit balance",
                      amount: "\$4,160.54",
                      bottomCardHeading: "Limit usage",
                      bottomCardTitleOne: "\$0.00",
                      bottomCardSubtitleOne: "Increase limits",
                      bottomCardSubtitleOneIcon: Icons.keyboard_arrow_right,
                      bottomCardTitleTwo: "\$112.99",
                      bottomCardSubtitleTwo: "available",
                      bottomCardSubtitleTwoIcon: Icons.info_outline,
                      bottomCardPercent: 22,
                      bgColor: AppColors.blue400Color,
                      borderColor: const Color(0xff212934),
                      onTapped: () {},
                    ),
                    const VSpacerWidget(size: 10.0),
                    DepositsDetailsBalanceCardThree(
                      title: "Credit balance",
                      amount: "-\$93.56",
                      bottomCardHeading: "Limit usage",
                      bottomCardTitleOne: "\$0.00",
                      bottomCardSubtitleOne: "Increase limits",
                      bottomCardSubtitleOneIcon: Icons.keyboard_arrow_right,
                      bottomCardTitleTwo: "\$112.99",
                      bottomCardSubtitleTwo: "available",
                      bottomCardSubtitleTwoIcon: Icons.info_outline,
                      bottomCardPercent: 22,
                      bgColor: AppColors.blue400Color,
                      borderColor: const Color(0xff212934),
                      onTapped: () {},
                    ),
                    const VSpacerWidget(size: 10.0),
                    DepositsDetailsBalanceCardThree(
                      title: "Credit balance",
                      titleColor: AppColors.whiteColor,
                      amount: "-\$93.56",
                      bottomCardHeading: "Limit usage",
                      bottomCardHeadingColor: AppColors.whiteColor,
                      bottomCardTitleOne: "\$0.00",
                      bottomCardTitleOneColor: AppColors.whiteColor,
                      bottomCardSubtitleOne: "Increase limits",
                      bottomCardSubtitleOneColor: AppColors.neutral100Color,
                      bottomCardSubtitleOneIcon: Icons.keyboard_arrow_right,
                      bottomCardSubtitleOneIconColor: AppColors.whiteColor,
                      bottomCardTitleTwo: "\$112.99",
                      bottomCardTitleTwoColor: AppColors.whiteColor,
                      bottomCardSubtitleTwo: "available",
                      bottomCardSubtitleTwoColor: AppColors.neutral100Color,
                      bottomCardSubtitleTwoIcon: Icons.info_outline,
                      bottomCardSubtitleTwoIconColor: AppColors.whiteColor,
                      bottomCardPercent: 22,
                      bottomCardPercentActiveColor: AppColors.whiteColor,
                      bottomCardPercentColor:
                          const Color.fromRGBO(245, 248, 250, 0.5),
                      bottomCardBgColor:
                          const Color.fromRGBO(255, 255, 255, 0.15),
                      bgColor: AppColors.blue400Color,
                      borderColor: AppColors.blue400Color,
                      onTapped: () {},
                    ),
                    const VSpacerWidget(size: 10.0),
                  ],
                ),
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "COLLAPSIBLE CARD"),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsCollapsibleOne(
                title: "This is a header / Title",
                titleColor: AppColors.textPrimaryColor,
                iconColor: AppColors.neutral500Color,
                subtitle:
                    "This is a subheader that further gives context to the header",
                itemOneTitle: "2 pending expenses",
                itemOneSubtitle: "\$560.50",
                bottomTitle: "View transactions",
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsCollapsibleOne(
                title: "This is a header / Title",
                titleColor: AppColors.textPrimaryColor,
                iconColor: AppColors.neutral500Color,
                subtitle:
                    "This is a subheader that further gives context to the header",
                itemOneTitle: "2 pending expenses",
                itemOneSubtitle: "\$560.50",
                bottomTitle: "View transactions",
                isOpen: true,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsCollapsibleTwo(
                title: "This is a header / Title",
                titleColor: AppColors.textPrimaryColor,
                iconColor: AppColors.neutral500Color,
                subtitle:
                    "This is a subheader that further gives context to the header",
                itemOneTitle: "Feb 28",
                itemOneSubtitle: "\$140.50",
                isOpen: true,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsAccordion(
                title: "This is a header / Title",
                subtitle:
                    "Lorem ipsum dolor sit amet consectetur. Amet egestas in sodales egestas at. Imperdiet et ac non eu urna. Pretium tortor ante gravida cursus hendrerit non. Viverra tellus adipiscing quis erat.",
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsAccordion(
                title: "This is a header / Title",
                subtitle:
                    "Lorem ipsum dolor sit amet consectetur. Amet egestas in sodales egestas at. Imperdiet et ac non eu urna. Pretium tortor ante gravida cursus hendrerit non. Viverra tellus adipiscing quis erat.",
                isOpen: true,
              ),
              const VSpacerWidget(size: 10.0),
              const HrWidget(
                borderColor: AppColors.neutral200Color,
                width: 0.5,
              ),
              const VSpacerWidget(size: 10.0),
              const HrWidget(
                borderColor: AppColors.neutral200Color,
                width: 1.0,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsContentDivider(
                text: "OR",
                dividerColor: AppColors.neutral200Color,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsH4Text(text: "Slider"),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsSliderOne(
                titleOne: "Label",
                titleTwo: "(Optional)",
                subtitle: "100%",
                percent: 50,
                onChanged: (a) {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsSliderOne(
                titleOne: "Label",
                titleTwo: "(Optional)",
                subtitle: "100%",
                percent: 20,
                onChanged: (a) {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsSliderTwo(
                titleOne: "",
                titleTwo: "",
                subtitleOne: "0",
                subtitleTwo: "100",
                percent: 30,
                onChanged: (a) {},
              ),
              const VSpacerWidget(size: 10.0),
              DepositsDetailsSliderTwo(
                titleOne: "Label",
                titleTwo: "(Optional)",
                subtitleOne: "0",
                subtitleTwo: "100",
                percent: 70,
                onChanged: (a) {},
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsTaskProgressOne(
                title: "Complete your profile",
                subtitle: "1 of 2 : Phone Number",
                percent: 80,
                sliderColor: AppColors.brand100Color,
              ),
              const VSpacerWidget(size: 10.0),
              const DepositsDetailsTaskProgressTwo(
                title: "Title",
                subtitle: "Step 1 of 4",
                percent: 20,
                sliderColor: AppColors.brand100Color,
              ),
              const VSpacerWidget(size: 10.0),
            ],
          ),
          const VSpacerWidget(size: 10.0),
        ],
      ),
    );
  }
}
