import 'package:flutter/material.dart';
import 'package:deposits_ui_kit_v2/deposits_ui_kit_v2.dart';

class FormDocPage extends StatefulWidget {
  const FormDocPage({super.key});

  @override
  State<FormDocPage> createState() => _FormDocPageState();
}

class _FormDocPageState extends State<FormDocPage> {
  String? selectedValue;
  final TextEditingController textEditingController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
      color: AppColors.whiteColor,
      child: Center(
        child: Column(
          children: [
            const DepositsH4Text(text: "Forms"),
            Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                DepositsFileUpload(
                    title: "Select image to upload",
                    supportedTypes: ".png, .jpg, .jpeg, .gif",
                    formState: DepositsFormUploadStates.uploading,
                    fileName: "Deposits_pitch.pdf",
                    fileSize: "2.3mb",
                    uploadPercent: 10,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                DepositsFileUpload(
                    title: "Select image to upload",
                    supportedTypes: ".png, .jpg, .jpeg, .gif",
                    formState: DepositsFormUploadStates.uploaded,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                DepositsFileUpload(
                    title: "Select image to upload",
                    supportedTypes: ".png, .jpg, .jpeg, .gif",
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                DepositsFileUpload(
                    title: "Select image to upload",
                    supportedTypes: ".png, .jpg, .jpeg, .gif",
                    formState: DepositsFormUploadStates.active,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                DepositsFileUpload(
                    title: "Select image to upload",
                    supportedTypes: ".png, .jpg, .jpeg, .gif",
                    formState: DepositsFormUploadStates.disabled,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                DepositsFileUpload(
                    title: "Select image to upload",
                    supportedTypes: ".png, .jpg, .jpeg, .gif",
                    formState: DepositsFormUploadStates.error,
                    errorText: "Only images are allowed here",
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsFileUploadInput(
                    title: "File uploader",
                    placeholder: "No file selected...",
                    onTapped: (a) {}),
                DepositsFileUploadInput(
                    title: "File uploader",
                    placeholder: "No file selected...",
                    fileName: "Deposits_pitch.pdf",
                    formState: DepositsFormUploadStates.active,
                    onTapped: (a) {}),
                DepositsFileUploadInput(
                    title: "File uploader",
                    placeholder: "No file selected...",
                    formState: DepositsFormUploadStates.disabled,
                    onTapped: (a) {}),
                DepositsFileUploadInput(
                    title: "File uploader",
                    placeholder: "No file selected...",
                    formState: DepositsFormUploadStates.error,
                    errorText: "kindly select an image",
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const [
                      'Option 1',
                      'Option 2',
                      'Option 3',
                      'Option 4',
                      'Option 5',
                      'Male',
                      'Female'
                    ],
                    size: DepositsFormSizeStates.large,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const [
                      'Male',
                      'Female',
                      'Option 1',
                      'Option 2',
                    ],
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Man', 'Woman'],
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Man', 'Woman'],
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsMultiSelect(
                    title: "Multiselect input",
                    items: const ['Option 1', 'Option 2', 'Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.large,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.medium,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.medium,
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.medium,
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.medium,
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.small,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsCountryDropDown(
                    title: "Country Select",
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.large,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.large,
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.active,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.disabled,
                    onTapped: (a) {}),
                DepositsDropDown(
                    title: "Dropdown",
                    items: const ['Male', 'Female'],
                    size: DepositsFormSizeStates.small,
                    formState: DepositsFormStates.error,
                    onTapped: (a) {}),
                const VSpacerWidget(size: 10.0),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.large,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.medium,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsNumberInput(
                  title: "Number Input",
                  placeholder: "0",
                  size: DepositsFormSizeStates.small,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsPhoneInput(
                  title: "Phone number",
                  countryCode: "+1",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.large,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.medium,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const VSpacerWidget(size: 5.0),
                DepositsSearchInput(
                  placeholder: "Search",
                  size: DepositsFormSizeStates.small,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsTextArea(
                  title: "Textarea",
                  placeholder: "Placeholder",
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsTextArea(
                  title: "Textarea",
                  placeholder: "Placeholder",
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsTextArea(
                  title: "Textarea",
                  placeholder: "Placeholder",
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsTextArea(
                  title: "Textarea",
                  placeholder: "Placeholder",
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsTextArea(
                  title: "Textarea",
                  placeholder: "Placeholder",
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.large,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.medium,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.active,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.cursor,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "",
                  initialValue: "",
                  formState: DepositsFormStates.disabled,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                DepositsFormField(
                  title: "Text Input",
                  placeholder: "Placeholder",
                  size: DepositsFormSizeStates.small,
                  errorText: "Error message",
                  initialValue: "",
                  formState: DepositsFormStates.error,
                  bgColor: AppColors.blackColor,
                  onTapped: (a) {},
                ),
                const HrWidget(borderColor: AppColors.blackColor),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
